# Default Meta
title: default title
description: default description
author: default author

email: info@hyde.io
phone: (123) 456-7890

facebook: https://www.facebook.com/
twitter: https://twitter.com/
instagram: https://www.instagram.com/
github: https://github.com/

# Jekyll Features
baseurl: "" # used for the navigation
exclude: [README.md]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# This will hide PDFs from the sitemap
defaults:
  -
    scope:
      path:            "pdf/*.pdf"
    values:
      sitemap:         false

sass:
  style: compressed
