baseurl: "" # used for the navbar
title: default title
description: default description



author: Joshua McSorley

email: info@mrhyde.io
phone: (123) 456-7890

facebook: https://www.facebook.com/joshuamcsorley
twitter: https://twitter.com/JJMcSorley
instagram: https://www.instagram.com/jjmcsorley
github: https://github.com/jjmcsorley

sass:
  style: compressed
