baseurl: "" # used for the navbar
title: default title
description: default description



name:
  first: Joshua
  middle: Joseph
  last: McSorley

email: joshuamcsorley@gmail.com
phone: (718) 577-7467

facebook: https://www.facebook.com/joshuamcsorley
twitter: https://twitter.com/JJMcSorley
instagram: https://www.instagram.com/jjmcsorley
github: https://github.com/jjmcsorley

sass:
  style: compressed
